#Docker-Compose for Jobs-postulantes

version: "3.3"

services:
  redis:
    image: redis:3.0.6
    ports:
      - "6379:6379"
    expose:
      - 6379
    networks:
      - applicants


  mongo:
    image: mongo:3.2.4
    container_name: "api-database"
    restart: always
    networks:
      - applicants
    expose:
      - 27017
    command: --smallfiles


  app:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - redis
      - mongo
    networks:
      - applicants

networks:
  applicants:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.128.1.0/24
