#Docker-Compose for Jobs-postulantes

version: "3.3"

services:
  redis:
    #platform: linux/x86_64
    image: redis:6.2.4
    ports:
      - "6379:6379"
    expose:
      - 6379
    networks:
      - applicants

  db:
    #platform: linux/x86_64
    #image: mysql:5.7
    image: mariadb:10.5.8
    restart: always
    environment:
      MYSQL_DATABASE: "challenge_db"
      MYSQL_USER: "db_user"
      MYSQL_PASSWORD: "Notebook123!"
      MYSQL_ROOT_PASSWORD: "Notebook123!"
    networks:
      - applicants
    expose:
      - 3306

  app:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - redis
      - db
    networks:
      - applicants

networks:
  applicants:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.128.1.0/24
