name: moba-api-integrator

server:
  port: 8080
  servlet.context-path: /challenge

management:
  health.defaults.enabled: false
  endpoints:
    web:
      exposure:
        include: info,metrics,health

spring.jackson.property-naming-strategy: SNAKE_CASE

management.info.git.mode: full

swagger:
  api:
    version: 1.0.0


# Fixer
fixer:
  baseUrl: http://data.fixer.io
  key: 32dcecc71324943b43693a4523ade931


# Ip Info
ipInfo:
  baseUrl: https://api.ip2country.info/

# Country Info
countryInfo:
  baseUrl: https://restcountries.eu


redis:
  ###***VALUE TO RUN ON LOCAL MODE***
  #host: localhost
  ###***VALUE TO RUN ON DOCKER MODE***
  host: redis
  port: 6379
  expiration: 300


#Logging
logging.description: true


spring:
  profiles:
    active: gcp,mysql
  jpa:
    show-sql: true
    open-in-view: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
  datasource:
    ###***VALUE TO RUN WITH WINDOWS LOCAL***
    #url: jdbc:mysql://localhost:3306/challenge_db
    ###***VALUE TO RUN WITH LINUX LOCAL***
    #url: jdbc:mysql://localhost:3306/challenge_db?verifyServerCertificate=false&useSSL=false&requireSSL=false
    ###***VALUE TO RUN WITH DOCKER***
    #url: jdbc:mysql://mysql:3306/challenge-db?verifyServerCertificate=false&useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
    ###***VALUE TO RUN WITH DOCKER-COMPOSE***
    #url: jdbc:mysql://db:3306/challenge_db
    ###***VALUE TO RUN WITH GOOGLE CLOUD RUN***
    url: jdbc:mysql://google/challenge?cloudSqlInstance=cloud-run-294818:us-central1:challenge-db&socketFactory=com.google.cloud.sql.mysql.SocketFactory
    #username: root
    #password: Notebook123!
    password: ${SECRETS_PASSWORD:Notebook123!}
    username: ${SECRETS_USER:root}
    initialization-mode: always
    driverClassName: com.mysql.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1