name: moba-api-integrator

server:
  port: 8080
  servlet.context-path: /challenge

management:
  health.defaults.enabled: false
  endpoints:
    web:
      exposure:
        include: info,metrics,health

spring.jackson.property-naming-strategy: SNAKE_CASE

management.info.git.mode: full

swagger:
  api:
    version: 1.0.0


# Fixer
fixer:
  baseUrl: http://data.fixer.io
  key: 32dcecc71324943b43693a4523ade931


# Ip Info
ipInfo:
  baseUrl: https://api.ip2country.info/

# Country Info
countryInfo:
  baseUrl: https://restcountries.eu


redis:
  #host: localhost
  host: redis
  port: 6379
  expiration: 300


#Logging
logging.description: true


spring:
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: create-drop
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        temp.use_jdbc_metadata_defaults: false
  datasource:
    #***asi me funciona si lo levanto en windows***
    #url: jdbc:mysql://localhost:3306/challenge_db
    #***asi me funciona si lo levanto en linux***
    #url: jdbc:mysql://localhost:3306/challenge_db?verifyServerCertificate=false&useSSL=false&requireSSL=false
    #***asi para levantarlo con docker***
    url: jdbc:mysql://db:3306/challenge_db?verifyServerCertificate=false&useSSL=false&requireSSL=false
    username: db_user
    password: Notebook123!
    driver-class-name: com.mysql.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1