name: moba-api-integrator

server:
  port: 8080
  servlet.context-path: /challenge

management:
  health.defaults.enabled: false
  endpoints:
    web:
      exposure:
        include: info,metrics,health

spring.jackson.property-naming-strategy: SNAKE_CASE

management.info.git.mode: full



swagger:
  api:
    version: 1.0.0


# Fixer
fixer:
  baseUrl: http://data.fixer.io
  key: 32dcecc71324943b43693a4523ade931


# Ip Info
ipInfo:
  baseUrl: https://api.ip2country.info/

# Country Info
countryInfo:
  baseUrl: https://restcountries.eu


redis:
  #host: localhost
  host: redis
  port: 6379
  expiration: 300


# MONGODB
#spring.data.mongodb.uri: mongodb://localhost:27017/EmployeeDB
spring.data.mongodb.host: api-database


#Logging
logging.description: true


